line-length = 120
format      = "grouped"
# Assume Python 3.9.
target-version = "py39"

# A list of file patterns to include when linting.
include = ["**/pyproject.toml", "*.ipynb", "*.py", "*.pyi"]

# Rules: https://beta.ruff.rs/docs/rules/
# Enable Pyflakes `E` and `F` codes by default.
select = [
    #default
    "E",    # pycodestyle error
    "F",    #flake8 error
    #extra
    "A",    # bultin shadowing
    "B",    # flake8 bugbear
    "BLE",  # aboid bare excepts
    "C4",   # simplify comprehensions
    "D",    # docstyle
    "DTZ",  # datetime errors
    "FBT",  # avoid boolean trap
    "G",    # logging format
    "I",    # flake8-isort import
    "N",    # pep8 naming
    "RET",  # return statements values
    "S",    # bandit
    "YTT",  # wrong usage of sys.info
    "B",  # flake8-bugbear
]

ignore = [
    "B008",   # do not perform function calls in argument defaults
    "BLE001", #Do not catch blind exception: {name}
    "C901",   # too complex
    "D107",   # Missing docstring in __init__
    "D203",   # 1 blank line required before class docstring
    "D213",   # Multi-line docstring summary should start at the second line
    "D417",   # Missing argument description in the docstring for {definition}: {name}
    "E501",   # Line too long ({width} > {limit} characters)
    "E501",   # line too long, handled by black
    "D100",
]

# Always autofix, but never try to fix `F401` (unused imports).
fix = true
unfixable = ["F401"]
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = ">=(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# Exclude a variety of commonly ignored directories (you can have some problems)
exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    ".venv"
]

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[flake8-quotes]
docstring-quotes = "double"

[pydocstyle]
convention = "google"

[isort]
known-third-party = ["fastapi", "pydantic", "starlette"]

[per-file-ignores]
"__init__.py" = ["D104", "F401", "I002"]
"test*.py"    = ["S101", "T201"]
